#NUMPY                                                         

NumPy is a Python package which stands for ‘Numerical Python’
Deals with multi diamensional arrays

In [1]:
import numpy as np 

In [2]:
#Array form a list
list1 = [1,2,3]
np.array(list1)



array([1, 2, 3])

In [3]:
#From matix
matrix = [[1,2,3],[4,5,6],[7,8,9]]

np.array(matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
#Array from existing list or tuple
a1=[2,3,4]
a3=[2,3,4,5,6]
a2=(9,8,7)
q12=np.asarray(a1)
print(q12)
q23= np.asarray(a2)
print(q23)
x = [(1,2,3),(4,5)] 
a = np.asarray(x) 
print (a)
#q34= np.asarray(a1,a3)
#print(q34)      #NO TOW ARGUMENT CAN PASS


[2 3 4]
[9 8 7]
[(1, 2, 3) (4, 5)]


In [5]:
#In-built
a = np.arange(24).reshape(4,6) 
print(a)
a.ndim #ndim shows the https://www.tutorialspoint.com/numpy/numpy_matplotlib.htmdiamension of the array

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


2

In [6]:
# start and stop and step parameters set 

x = np.arange(10,20,2) 
x

array([10, 12, 14, 16, 18])

In [7]:
print(a)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [8]:
#Reshaping existing above 
a.reshape(2,12)


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [9]:
#shape,
a.shape


(4, 6)

In [12]:
#Array attribute(itemsize) returns the length of each element of array in bytes.xx= np.array([1,2,3,4,5,5,7])
print(a.itemsize)
a.dtype

4


dtype('int32')

In [13]:

x = np.array([1,2,3,4,5,6,7],dtype = np.int8) #explicitly changing datattype

print (x.itemsize)
x.dtype
#x[1:7:2]

1


dtype('int8')

#Array Creation Routines- empty,zeros,ones

In [15]:
q1=np.empty([3,2])
print(q1)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [14]:
q2= np.zeros(3)
q2

array([0., 0., 0.])

In [16]:
q3= np.ones(4)
q3

array([1., 1., 1., 1.])

In [17]:
#range function
list = range(5) 
list

range(0, 5)

In [18]:
#Return evenly spaced numbers over a specified interval.
w= np.linspace(10,20,10)
w

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [19]:
x = np.array([[ 0,  1,  2],[ 3,  4,  5],[ 6,  7,  8],[ 9, 10, 11]]) 
print(x)
print("Extracted the element from existing array above")
y=x[[0,1,2,3],[0,1,1,2]]#Extract elements from (0,0),(1,1),(2,1),(3,2) of x
print(y)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
Extracted the element from existing array above
[ 0  4  7 11]


In [20]:
l1 = [1,2,3,4]
l2  = [5,6,7,8]

#l1*l2


#can't multiply sequence by non-int of type 'list'
#So we need numpy array

In [21]:
#Multiplication
array1 = np.array([1,2,3,4])
array2 = np.array([5,6,7,8])
array1*array2

array([ 5, 12, 21, 32])

In [22]:
k=[14,5,6,10,14]
w=np.array(w)
w

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [23]:
#performing addition operation
print(w+2)

for i in k:
    i+=2
    print(i)
#Other arthematic operations can also be performed

[12.         13.11111111 14.22222222 15.33333333 16.44444444 17.55555556
 18.66666667 19.77777778 20.88888889 22.        ]
16
7
8
12
16


In [24]:
#Some universal operations 
arr = np.arange(0,10)
print("Square root")
print(np.sqrt(arr))
print("Exponential")
print(np.exp(arr))
print("Maximum value in an array")
print(np.max(arr))
#Other operators like min,sin,log etc can be applied

Square root
[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]
Exponential
[1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01
 5.45981500e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03
 2.98095799e+03 8.10308393e+03]
Maximum value in an array
9


In [25]:
y = np.array([24,32,67,96,33])
print(y>32)
y[y>32]

[False False  True  True  True]


array([67, 96, 33])

In [26]:
#in numpy it is arange
import numpy as np
l1= np.arange(5000)
l1

array([   0,    1,    2, ..., 4997, 4998, 4999])

In [27]:
#import time 
a = np.arange(10000)
%timeit a + 1  #simple to perdorm to know the time
a

11.3 µs ± 267 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


array([   0,    1,    2, ..., 9997, 9998, 9999])

In [28]:
list1 = range(1, 100000)
%timeit

for i in list1:
    i + 1

In [30]:
#Identity matrix
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])